version: "3.9"
services:
  backend:
    build: ./backend
    container_name: futurestack-backend
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: futurestack-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
